name: generate-snake

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:
  
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake files
        uses: Platane/snk@v3
        with:
          github_user_name: pcavalheiroo
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
